version: '3.8'

services:
  # Frontend React app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_API_URL=http://100.119.251.66:8080
      - NODE_ENV=development
    command: npm run dev
    container_name: fight-app-frontend
    networks:
      - fight-app_network

  # Backend Node.js server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/fightpick_db
      - OLLAMA_URL=http://100.119.251.66:11434
      - PORT=8080
    command: npm run dev
    volumes:
      - ./server/src:/app/server/src
    depends_on:
      - db
    container_name: fight-app-backend

  # PostgreSQL database
  db:
    container_name: fight-app-db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fightpick_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fight-app_network

volumes:
  postgres_data: 

networks:
  fight-app_network:
    driver: bridge
