FROM node:18

WORKDIR /app/server

# Copy package files
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY server .

EXPOSE 8080

# Use nodemon for development
CMD ["npm", "run", "dev"] 